server.port: ${PORT:8080}
spring.data.mongodb.uri: mongodb+srv://admin:kwggwld@cluster0.j91yp.mongodb.net/StartupDB?retryWrites=true&w=majority
spring.data.mongodb.database: StartupDB
spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration